{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "e86f279c_4a736dab",
        "filename": "autoninja.py",
        "patchSetId": 1
      },
      "lineNbr": 461,
      "author": {
        "id": 1366072
      },
      "writtenOn": "2025-04-09T05:33:05Z",
      "side": 1,
      "message": "Do you already know when would this happen? I don\u0027t think the developer can fix this situation by themselves. At very least, it should mention `please try gn clean` etc.",
      "range": {
        "startLine": 455,
        "startChar": 0,
        "endLine": 461,
        "endChar": 0
      },
      "revId": "5482a8657f7af04bcb868b67b8d02622547b7af3",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}